### PR TITLE
[SofaScene] Enabling retrieval of components by abstract types (not i…

### PR DESCRIPTION
**Pull request by marques-bruno**
Hi guys,

This PR follows #2. I would really like your opinion on this PR since I'm really not sure that it's a great idea.
The goal is to be able to retrieve all components in the scene, using a visitor, that inherits the same **abstract** base class.

Before it was not possible, because the base class had to be registered in the ObjectFactory, and thus be instantiatable.
So what I'm doing instead is comparing the BaseClass::className with the one passed as argument to the visitor, in each BaseObject.

It's less clean, but it's the only way I found to filter out with abstract classes, which I think is an important feature in a GUI that allows for custom widgets per components.

### CODE REVIEW

**Comment by damienmarchal** [comment]
I merge everything because things are too slow on SofaQtQuick...

**Comment by marques-bruno** [comment]
That's too bad though.. Shouldn't we start including those in the wednesday's PR reviews? There are only very few PRs on SofaQtQuick, it wouldn't take much time

**Comment by damienmarchal** [comment]
Actually they are :) 
but we always forgot.

**Comment by marques-bruno** [comment]
Oh... Well next time I'll have an ongoing pr I'll try to bring it up :)

**Comment by damienmarchal** [comment]
Actually I don't think there is a need to handle those PR with the same level of rigor a the core SOFA, and I'm more in favor of having a 
dev branch with merging as early as we want
and a 
master branch with merging when some people confirm that the dev branch is at least compiling.

**Pull request merged**
