### PR TITLE
[REFACTOR]: Plugin Restructuration.

### PR DESCRIPTION
**Pull request by marques-bruno**
- removed qtQuickSofa project
- restructured repository's hierarchy:
```
.
├── compliant_qtquickgui
├── image_qtquickgui
├── runSofa2
└── SofaQtQuickGUI
└── doc
```
vs
```
.
├── applications-dev
│   ├── plugins
│   │   ├── compliant_qtquickgui
│   │   ├── image_qtquickgui
│   │   └── SofaQtQuickGUI
│   └── projects
│       └── runSofa2
└── doc
```
- Removed hand-made cmake target deployment code, replaced with clean SofaMacros
- Renamed preprocessor define SOFA_SOFAQTQUICK_SRC_DIR to SOFAQTQUICK_QML_DIR for the FileSystemWatcher

TODO (in another PR maybe):
- Move compliant code in compliant plugin
- Move image code in image plugin
- refactor cmake macros used in runSofa & runSofa2 to list loaded default plugins

### CODE REVIEW

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
*Added qt5-webengine* [ci-build]

**Comment by marques-bruno** [comment]
Oh... of course. It fails since the dev branch only builds against the sofaqtquickgui_dev branch of SOFA...

**Comment by damienmarchal** [comment]
ouch.

**Pull request closed without merging**
